bark/attendances/routes.py
from datetime import datetime, timedelta, timezone
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from bark import db
from bark.attendances.forms import CheckAttendanceForm, CreateAttendanceForm
from bark.models import Attendance, Course
from bark.courses.forms import CreateCourseForm, JoinCourseForm

attendances = Blueprint('attendances', __name__)

@attendances.route('/attendances/create/<int:course_id>',  methods=['GET', 'POST'])
@login_required
def create_attendance(course_id):
    #check if user is a student
    if current_user.type == 'Student':
        return redirect(url_for('courses.view_course', course_id = course_id))
    
    form = CreateAttendanceForm()
    
    if form.validate_on_submit():
        course = Course.query.filter_by(id=course_id).first()
        attendance = Attendance(date = datetime.now(timezone.utc), 
                                code = form.code.data, 
                                expires = form.expires.data, 
                                expiretime = datetime.now(timezone.utc) + timedelta(minutes = form.expirestime.data))
        db.session.add(attendance) 
        course.attendances.append(attendance)
        db.session.commit()
        flash(f'Created Attendance!', 'success')
        return redirect(url_for('courses.view_course', course_id = course_id))
    
    #load form
    return render_template('create_attendance.html', title = 'Create Attendance', form = form)

@attendances.route('/attendances/check/<int:course_id>', methods=['GET', 'POST'])
@login_required
def check_attendance(course_id):
    #check if user is a student
    if current_user.type == 'Professor':
        return redirect(url_for('courses.view_course', course_id = course_id))
    
    form = CheckAttendanceForm()
    
    if form.validate_on_submit():
        
        attendance = Attendance.query.filter_by(code=form.code.data).first()
        current_user.attendances.append(attendance)
        db.session.commit()
        flash(f'Created Attendance!', 'success')
        return redirect(url_for('courses.view_course', course_id = course_id))
    
    #load form
    return render_template('check_attendance.html', title = 'Check Attendance', form = form)

bark/courses/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from bark import db
from bark.models import Course
from bark.courses.forms import CreateCourseForm, JoinCourseForm

courses = Blueprint('courses', __name__)

#Display all of the user's courses
@courses.route('/courses')
@login_required
def my_courses():
    #get courses from current user
    courses = current_user.courses
    
    #load html
    return render_template('courses.html', title = 'Courses', courses = courses)

#Let professors add courses
@courses.route('/courses/create_course' , methods=['GET', 'POST'])
@login_required
def create_course():
    #check if user is a student
    if current_user.type == 'Student':
        return redirect(url_for('courses.my_courses'))
    
    #get CreateCourseForm
    form = CreateCourseForm()
    
    #submitting the form
    if form.validate_on_submit():
        course = Course(title = form.title.data, code = form.code.data)
        db.session.add(course)
        current_user.courses.append(course)
        db.session.commit()
        flash(f'New Course Created!', 'success')
        return redirect(url_for('courses.my_courses'))
    
    #load form
    return render_template('create_course.html', title = 'Create Course', form = form)
    
        
#Let students join courses
@courses.route('/courses/join_course', methods=['GET', 'POST'])
@login_required
def join_course():
    #check if user is a professor
    if current_user.type == 'Professor':
        return redirect(url_for('courses.my_courses'))
    
    #get JoinCourseForm
    form = JoinCourseForm()
    
    #submitting the form
    if form.validate_on_submit():
        course = Course.query.filter_by(code=form.code.data).first()
        if course:
            current_user.courses.append(course)
            db.session.commit()
            flash(f'New Course Joined!', 'success')
            return redirect(url_for('courses.my_courses'))
        else:
            flash(f'No course found!', 'failure')
    
    #load form
    return render_template('join_course.html', title = 'Join Course', form = form)

@courses.route('/courses/<int:course_id>')
@login_required
def view_course(course_id):
    course = Course.query.filter_by(id=course_id).first()
    return render_template('course.html', title = 'Course', course = course)

@courses.route('/courses/<int:course_id>/delete')
@login_required
def delete_course(course_id):
    #check if user is a student
    if current_user.type == 'Student':
        return redirect(url_for('courses.view_course', course_id = course_id))
    course = Course.query.filter_by(id=course_id).first()
        
    db.session.delete(course)
    db.session.commit()
    return redirect(url_for('courses.my_courses'))

@courses.route('/courses/<int:course_id>/leave')
@login_required
def leave_course(course_id):
    #check if user is a professor
    if current_user.type == 'Professor':
        return redirect(url_for('courses.view_course', course_id = course_id))
    course = Course.query.filter_by(id=course_id).first()
    
    try:
        current_user.courses.remove(course)
    except ValueError as e:
        print(f"Error: {e}")
    return redirect(url_for('courses.my_courses'))

bark/main/routes.py
from datetime import datetime, timezone
from flask import render_template, Blueprint
from bark import db, bcrypt
from bark.models import User, Course, Attendance

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Home')

#Create Dummy Data
@main.route("/create")
def create():
    hashed_password = bcrypt.generate_password_hash("test").decode('utf-8')
    testuser = User(email = 'test@gmail.com', password = hashed_password, type = 'Student')
    testuser2 = User(email = 'test2@gmail.com', password = hashed_password, type = 'Professor')
    testcourse = Course(title = 'test', code = 'test')
    testcourse2 = Course(title = 'test2', code = 'test2')
    testattendance = Attendance(date = datetime.now(timezone.utc), code = 'test', expires = False)
    db.session.add(testuser)
    db.session.add(testattendance)
    db.session.add(testcourse)
    db.session.add(testcourse2)
    db.session.add(testuser2)
    
    testuser.courses.append(testcourse)
    testuser2.courses.append(testcourse)
    testuser.attendances.append(testattendance)
    testcourse.attendances.append(testattendance)
    db.session.commit()
    
    users = User.query.all()
    courses = Course.query.all()
    attendances = Attendance.query.all()
    print(users)
    print(courses)
    print(attendances)
    
    print("attend users: ")
    print(testattendance.users)
    return render_template('create.html', posts = users)

@main.route("/check")
def check():

    users = User.query.all()
    courses = Course.query.all()
    attendances = Attendance.query.all()
    print(users)
    print(courses)
    print(attendances)
    return render_template('create.html', posts = users)

bark/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from bark import db, bcrypt
from bark.users.forms import RegistrationForm, LoginForm
from bark.models import User
from flask_login import login_user, current_user, logout_user, login_required
from bark.users.utils import send_authentication_email
users = Blueprint('users', __name__)

#Creates user and sends email to validate the email.
@users.route("/register", methods=['GET', 'POST'])
def register():
    #check that user is not currently logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    #get registration form
    form = RegistrationForm()
    
    #submitting form
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(email = form.email.data, password = hashed_password, type = 'Student')
        send_authentication_email(user)
        flash(f'Email sent for authentication', 'info')
        return redirect(url_for('users.login'))

    #load form 
    return render_template('register.html', title = 'Register', form = form)

#Validates the user
@users.route("/register/<token>", methods=['GET', 'POST'])
def validate_user(token):
    #check that user is not currently logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    #check if valid token is provided
    userdict = User.verify_token(token)
    if not userdict:
        flash(f'Invalid or expired token! Please register again!', 'warning')
        return redirect(url_for('users.register'))
        
    print(userdict)
    #if valid token provided, update user
    user = User(email = userdict["email"], password = userdict["password"], type = userdict["type"])
    db.session.add(user)
    db.session.commit()
    flash(f'User validated! You may now log in!')
    return redirect(url_for('users.login'))

#Login the user
@users.route("/login", methods=['GET', 'POST'])
def login():
    #check that user is not currently logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    #get login form
    form = LoginForm()
    
    #submitting form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            flash(f'Logged In!', 'success')
            return redirect(url_for('next_page')) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Login Failed!', 'failure')
    
    #load form
    return render_template('login.html', title = 'Login', form = form)

#Logout User
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


    

bark/templates/check_attendance.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a new course</legend>
                <div class="form-group">
                    {{ form.code.label(class="form-control-label") }}
                    {% if form.code.errors %}
                        {{ form.code(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.code.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.code(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    

{% endblock content %}

bark/templates/course.html
{% extends "layout.html" %} 
{% block content %}
    <h1>{{ course.title }}</h1>
    <p>{{ course.code }}</p>
    {% if current_user.type == 'Professor' %}
        <a href="{{url_for('attendances.create_attendance', course_id = course.id)}}">Create Attendance</a>
        <a href="{{ url_for('courses.delete_course', course_id = course.id)}}">Delete Course</a>
    {% else %}
        <a href="{{ url_for('attendances.check_attendance', course_id = course.id)}}">Check for Attendance</a>
        <a href="{{ url_for('courses.leave_course', course_id = course.id)}}">Leave Course</a>
    {% endif %}

        <div>
            attendance history:
            {{ course.attendances }}
            {% for attendance in course.attendances %}
            <div>
                <p>{{attendance.users}}</p>
            </div>
            {% endfor %}
        </div>
{% endblock content %}

bark/templates/courses.html
{% extends "layout.html" %} 
{% block content %}
    <h1>Your Courses: </h1>
    {% if current_user.type == 'Professor' %}
        <a href="{{ url_for('courses.create_course')}}">Create Course</a>
    {% else %}
        <a href="{{ url_for('courses.join_course')}}">Join Course</a>
    {% endif %}
    {% for course in courses%}
        <div>
            <h2><a href="{{ url_for('courses.view_course', course_id = course.id)}}">{{ course.title }}</a></h2>
        </div>
    {% endfor%}
{% endblock content %}

bark/templates/create.html
{% extends "layout.html" %} 
{% block content %}
<p>users:</p>
{% for post in posts.items %}
    <p>{{ post.email }}</p>
{% endfor %} 
{% endblock content %}

bark/templates/create_attendance.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a new course</legend>
                <div class="form-group">
                    {{ form.code.label(class="form-control-label") }}
                    {% if form.code.errors %}
                        {{ form.code(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.code.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.code(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.expires(class="form-check-input") }}
                    {{ form.expires.label(class="form-check-label") }}
                </div>
                <div class="form-group">
                    {{ form.expirestime.label(class="form-control-label") }}
                    {% if form.expirestime.errors %}
                        {{ form.expirestime(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.expirestime.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.expirestime(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    

{% endblock content %}

bark/templates/create_course.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create a new course</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.code.label(class="form-control-label") }}
                    {% if form.code.errors %}
                        {{ form.code(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.code.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.code(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    

{% endblock content %}

bark/templates/home.html
{% extends "layout.html" %} 
{% block content %}
<h1>Welcome to Bark</h1>
<p>Bark is a free alternative to attendance checker type apps like TopHat!</p>
{% endblock content %}

bark/templates/join_course.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join a new course</legend>
                <div class="form-group">
                    {{ form.code.label(class="form-control-label") }}
                    {% if form.code.errors %}
                        {{ form.code(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.code.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.code(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    

{% endblock content %}

bark/templates/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        {% if title %}
        <title>Bark - {{ title }} </title>
        {% else %}
        <title>Bark</title>
        {% endif %}
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>

        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Bark</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                  </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                      <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                      <a class="nav-item nav-link" href="{{ url_for('courses.my_courses') }}">Courses</a>
                    {% else %}
                      <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                      <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </nav>
          </header>

            <main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif%}
          {% endwith %}
        {% block content %}{% endblock %}
        </div>
    </div>
    </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </body>
</html>

bark/templates/login.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In to Bark!</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="#"> Forgot Password?</a>
                </small>
            </div>
            
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
        </small>
    </div>

{% endblock content %}

bark/templates/register.html
{% extends "layout.html" %} 
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Bark Today!</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {%endfor%}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>

{% endblock content %}